// Generated by CoffeeScript 1.10.0
(function() {
  var exec, http, last_payload, querystring;

  http = require('http');

  querystring = require('querystring');

  exec = require('child_process').exec;

  last_payload = {};

  http.createServer(function(request, response) {
    var body;
    if (request.method === 'GET') {
      response.writeHead(200, {
        'Content-Type': 'text/html'
      });
      response.write('<html><body><pre>');
      response.write(JSON.stringify(last_payload, null, '\\u9'));
      response.write('</pre></body></html>');
      response.end();
    } else {
      body = '';
      request.on('data', function(chunk) {
        body += chunk.toString();
      });
      request.on('end', function() {
        console.log('request end', querystring.parse(body));
        if (body) {
          last_payload = JSON.parse(querystring.parse(body).payload) || {};
          console.log(new Date, request.method, request.url, last_payload);
          exec('./deploy.sh', function(error, stdout, stderr) {
            response.writeHead(200, {
              'Content-Type': 'text/plain'
            });
            response.end(error ? stderr : stdout);
          });
        }
      });
    }
  }).listen(4567);

  console.log('Server running at http://*:4567/');

}).call(this);
