// Generated by CoffeeScript 1.9.3
(function() {
  var exec, http, last_payload, querystring;

  http = require('http');

  querystring = require('querystring');

  exec = require('child_process').exec;

  last_payload = {};

  http.createServer(function(request, response) {
    var body;
    if (request.method === 'GET') {
      response.writeHead(200, {
        'Content-Type': 'text/html'
      });
      response.write('<html><body><pre>');
      response.write(JSON.stringify(last_payload, null, '\\u9'));
      response.write('</pre></body></html>');
      response.end();
    } else {
      body = '';
      request.on('data', function(chunk) {
        body += chunk.toString();
      });
      request.on('end', function() {
        last_payload = JSON.parse(body);
        return exec('./deploy.sh', function(error, stdout, stderr) {
          if (error) {
            console.log(error);
          } else {
            console.log(stdout);
          }
          response.writeHead(200, {
            'Content-Type': 'text/plain'
          });
          response.end(error ? stderr : stdout);
        });
      });
      return;
    }
  }).listen(4567);

  console.log('Server running at http://*:4567/');

}).call(this);

//# sourceMappingURL=deploy.js.map
